import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Providers } from '@/components/providers/provider'
import { NavigationWrapper } from '@/components/appCompnent/userComponent/navigation/navigationWrapper'
import ClientToaster from '@/components/appCompnent/ClientToaster'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // const isUser = session?.user.role !== "admin";
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NavigationWrapper>
          <Providers>{children}</Providers>
        </NavigationWrapper>
        <ClientToaster />
      </body>
    </html>
  )
}
